# Generated by Django 2.2 on 2020-03-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('NewsId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('ReadFrequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('NewsTagId', models.AutoField(primary_key=True, serialize=False)),
                ('TagName', models.CharField(max_length=100)),
                ('TagFrequency', models.IntegerField()),
            ],
        ),
    ]
