# Generated by Django 2.2 on 2020-03-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='body',
        ),
        migrations.AddField(
            model_name='news',
            name='URL',
            field=models.URLField(default='https://www.cbc.ca/news'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='News',
            field=models.ManyToManyField(related_name='newstag', to='news.News'),
        ),
    ]
