# Generated by Django 2.2 on 2020-03-15 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200310_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstag',
            options={'ordering': ['-TagFrequency']},
        ),
        migrations.RemoveField(
            model_name='newstag',
            name='News',
        ),
        migrations.AddField(
            model_name='news',
            name='Created_Date',
            field=models.DateField(auto_created=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='URL',
            field=models.URLField(default='www.cbc.ca', max_length=1000),
        ),
    ]
